/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [OwnersPartyName]
      ,[OwnersName]
      ,[Abil_Name]
      ,[Abil_Level]
      ,[DescrOfAbility]
      ,[AbilIsActive]
      ,[ManaCost]
      ,[ManaRegenCost]
      ,[HpCost]
      ,[DurationMax]
      ,[DurationElapsed]
      ,[NoOfEntitiesAffectedMax]
      ,[TargetEntitiesAffected]
      ,[HpEffect]
      ,[TargetRange]
      ,[SaveType]
  FROM [FantasyGame].[dbo].[Ability]